### ISSUE TITLE
GPU not being recognized by mxnet backend in Colab

### ISSUE THREAD

**Issue by arijitgupta42** [Tessellate-Imaging/monk_v1#46]
When running the gluon_prototype on Kaggle with default parameters,
```python
gtf.Default(dataset_path=train_path,
           model_name="densenet121",
           freeze_base_network=False,
           num_epochs=5)
```
The Use Gpu is automatically being set to false 
```
Model Params
    Model name:           densenet121
    Use Gpu:              False
    Use pretrained:       True
    Freeze base network:  False

Model Details
    Loading pretrained model

```

and the following warning is raised in the Kaggle Notebook:
```
/kaggle/working/monk_v1/monk/system/imports.py:160: UserWarning: GPU not accessible yet requested.
  warnings.warn(msg)
```

**Comment by abhi-kumar** [comment]
It's because GPUtil library is unable to find gpu in Kaggle

import GPUtil
GPUs = GPUtil.getGPUs()

>>> GPUs
>>>[]

Will work out a solution for this very soon

**Comment by abhi-kumar** [comment]
Further analysis:

GPUtil works on nvidia-smi command...

Before kaggle site was refurbished by google the command nvidia-smi worked on kaggle... It doesn't these days it seems...

**Comment by arijitgupta42** [comment]
But Kaggle only allows access to data files on its notebooks. The externally imported library files cannot be modified. Is there a way to do that?

**Comment by THEFASHIONGEEK** [comment]
@arijitgupta42 fork the repo and make changes as mentioned in your repo. Import it from your repo.

**Comment by abhi-kumar** [comment]
@arijitgupta42  Necessary changes have been made. Please check if the issue is resolved at your end or not.

**Comment by arijitgupta42** [comment]
Yes, It's working now.

**Comment by arijitgupta42** [comment]
When running the gluon_prototype on Colab with default parameters,
```python
gtf.Default(dataset_path=train_path,
           model_name="densenet121",
           freeze_base_network=False,
           num_epochs=5)
```
The Use Gpu is automatically being set to false 
```
Model Params
    Model name:           densenet121
    Use Gpu:              False
    Use pretrained:       True
    Freeze base network:  False

Model Details
    Loading pretrained model

```


and the following warning is raised in the Colab Notebook:
```
/content/monk_v1/monk/system/imports.py:160: UserWarning: GPU not accessible yet requested.
  warnings.warn(msg)
```

**Comment by abhi-kumar** [comment]
Please make sure you are setting the right runtime and using the latest version of monk.

![Screenshot(66)](https://user-images.githubusercontent.com/5428112/77551279-26baf780-6ed8-11ea-87fb-4e1527baf5ef.png)

I tried the same using similar settings are yours. And it automatically set the GPU as True.

Could you please check the runtime and let us know if the error still persists
